In [ ]:
pip install matplotlib

In [ ]:
## Importing libraries

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, MinMaxScaler

In [59]:
## Reading the file

df = pd.read_csv('F:\KN Academy - Projects\Machine Learning\Telecom Customer Churn\Customer-Churn (1).csv')

In [60]:
df.head(5)

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [61]:
df.Churn.value_counts()/len(df)*100

Churn
No     73.463013
Yes    26.536987
Name: count, dtype: float64

## **Churn Rate**: 26.53%

- Which means, 26.53% of the customers churn out of this telecom company

In [62]:
## Divide data into X and y - X (Independent features), y(Dependent variable)

# Define y (target variable)
y = df['Churn']

# Define X (features) by dropping 'customerID' and 'Churn'
X = df.drop(columns=['customerID', 'Churn'])

# Optional: Verify the shapes
print("Shape of X:", X.shape)
print("Shape of y:", y.shape)

Shape of X: (7043, 19)
Shape of y: (7043,)

In [63]:
X.isna().sum()

gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
dtype: int64

## Train Test Split

In [64]:
X = pd.get_dummies(X, drop_first=True)
y = df['Churn'].map({'No': 0, 'Yes': 1})

In [65]:
X.isna().sum()

SeniorCitizen          0
tenure                 0
MonthlyCharges         0
gender_Male            0
Partner_Yes            0
                      ..
TotalCharges_997.75    0
TotalCharges_998.1     0
TotalCharges_999.45    0
TotalCharges_999.8     0
TotalCharges_999.9     0
Length: 6559, dtype: int64

In [66]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

## Model Building

In [67]:
model_dt = DecisionTreeClassifier()
model_dt.fit(X_train, y_train)

DecisionTreeClassifier()

In [68]:
y_pred_dt = model_dt.predict(X_test)

In [69]:
print(classification_report(y_test, y_pred_dt))

              precision    recall  f1-score   support

           0       0.83      0.88      0.85      1033
           1       0.60      0.49      0.54       376

    accuracy                           0.78      1409
   macro avg       0.71      0.69      0.70      1409
weighted avg       0.77      0.78      0.77      1409

In [70]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   object
 20  Churn             7043 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.1+ MB

## Initial Insights

- Base model has a accuracy of 76% which is not reliable because of the imbalanced dataset
- TotalCharges needs to be a float/int type (Data Cleaning)
- Need to perform Feature Scaling

## Data Cleaning

In [71]:
telco_data = df.copy()

In [73]:
# 1. Reload your fresh dataset so you get your rows back
# telco_data = pd.read_csv('your_file_name.csv') # Replace with your actual file path

# 2. Convert to numeric - this safely turns all types of empty spaces into NaN
telco_data['TotalCharges'] = pd.to_numeric(telco_data['TotalCharges'], errors='coerce')

# 3. Drop ONLY the rows where TotalCharges is now NaN
telco_data = telco_data.dropna(subset=['TotalCharges'])

In [74]:
telco_data.TotalCharges.head(10)

0      29.85
1    1889.50
2     108.15
3    1840.75
4     151.65
5     820.50
6    1949.40
7     301.90
8    3046.05
9    3487.95
Name: TotalCharges, dtype: float64

In [ ]:
# telco_data.TotalCharges = pd.to_numeric(telco_data.customerID, errors='coerce')

In [75]:
telco_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7032 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7032 non-null   object
 1   gender            7032 non-null   object
 2   SeniorCitizen     7032 non-null   int64
 3   Partner           7032 non-null   object
 4   Dependents        7032 non-null   object
 5   tenure            7032 non-null   int64
 6   PhoneService      7032 non-null   object
 7   MultipleLines     7032 non-null   object
 8   InternetService   7032 non-null   object
 9   OnlineSecurity    7032 non-null   object
 10  OnlineBackup      7032 non-null   object
 11  DeviceProtection  7032 non-null   object
 12  TechSupport       7032 non-null   object
 13  StreamingTV       7032 non-null   object
 14  StreamingMovies   7032 non-null   object
 15  Contract          7032 non-null   object
 16  PaperlessBilling  7032 non-null   object
 17  PaymentMethod     7032 non-null   object
 18  MonthlyCharges    7032 non-null   float64
 19  TotalCharges      7032 non-null   float64
 20  Churn             7032 non-null   object
dtypes: float64(2), int64(2), object(17)
memory usage: 1.2+ MB

In [76]:
telco_data.loc[telco_data['TotalCharges'].isnull() == True]

Empty DataFrame
Columns: [customerID, gender, SeniorCitizen, Partner, Dependents, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges, Churn]
Index: []

[0 rows x 21 columns]

In [77]:
telco_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7032 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7032 non-null   object
 1   gender            7032 non-null   object
 2   SeniorCitizen     7032 non-null   int64
 3   Partner           7032 non-null   object
 4   Dependents        7032 non-null   object
 5   tenure            7032 non-null   int64
 6   PhoneService      7032 non-null   object
 7   MultipleLines     7032 non-null   object
 8   InternetService   7032 non-null   object
 9   OnlineSecurity    7032 non-null   object
 10  OnlineBackup      7032 non-null   object
 11  DeviceProtection  7032 non-null   object
 12  TechSupport       7032 non-null   object
 13  StreamingTV       7032 non-null   object
 14  StreamingMovies   7032 non-null   object
 15  Contract          7032 non-null   object
 16  PaperlessBilling  7032 non-null   object
 17  PaymentMethod     7032 non-null   object
 18  MonthlyCharges    7032 non-null   float64
 19  TotalCharges      7032 non-null   float64
 20  Churn             7032 non-null   object
dtypes: float64(2), int64(2), object(17)
memory usage: 1.2+ MB

In [78]:
telco_data.head(5)

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.50,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [79]:
telco_data.tenure.max()

np.int64(72)

In [80]:
import pandas as pd

# Define the bin edges (0 to 72, stepping by 12 months)
bins = [0, 12, 24, 36, 48, 60, 72]

# Define the labels for each bin
labels = ['1-12', '13-24', '25-36', '37-48', '49-60', '61-72']

# Create the new binned column
telco_data['tenure_bin'] = pd.cut(telco_data['tenure'], bins=bins, labels=labels, include_lowest=True)

# Optional: Check the result
print(telco_data[['tenure', 'tenure_bin']].head(10))
print(telco_data['tenure_bin'].value_counts().sort_index())

   tenure tenure_bin
0       1       1-12
1      34      25-36
2       2       1-12
3      45      37-48
4       2       1-12
5       8       1-12
6      22      13-24
7      10       1-12
8      28      25-36
9      62      61-72
tenure_bin
1-12     2175
13-24    1024
25-36     832
37-48     762
49-60     832
61-72    1407
Name: count, dtype: int64

In [81]:
telco_data.head(5)

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn,tenure_bin
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No,1-12
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,No,No,No,One year,No,Mailed check,56.95,1889.50,No,25-36
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes,1-12
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No,37-48
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes,1-12

In [82]:
# Drop rows where TotalCharges is NaN
telco_data = telco_data.dropna(subset=['TotalCharges'])

In [83]:
## Divide data into X and y - X (Independent features), y(Dependent variable)

# Define y (target variable)
y = telco_data['Churn']

# Define X (features) by dropping 'customerID' and 'Churn'
X = telco_data.drop(columns=['customerID', 'Churn', 'tenure'])

# Optional: Verify the shapes
print("Shape of X:", X.shape)
print("Shape of y:", y.shape)

Shape of X: (7032, 19)
Shape of y: (7032,)

In [84]:
X = pd.get_dummies(X, drop_first=True)
y = telco_data['Churn'].map({'No': 0, 'Yes': 1})

In [85]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

## Feature Scaling

In [86]:
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [87]:
model_dt2 = DecisionTreeClassifier()
model_dt2.fit(X_train, y_train)

y_pred_dt2 = model_dt2.predict(X_test)

In [88]:
print(classification_report(y_test, y_pred_dt2))

              precision    recall  f1-score   support

           0       0.83      0.80      0.81      1038
           1       0.48      0.52      0.50       369

    accuracy                           0.73      1407
   macro avg       0.65      0.66      0.66      1407
weighted avg       0.74      0.73      0.73      1407

## Feature Scaling - MinMaxScaler

In [89]:
mms = MinMaxScaler()
X_train_mms = mms.fit_transform(X_train)
X_test_mms = mms.transform(X_test)

In [90]:
model_dt3 = DecisionTreeClassifier()
model_dt3.fit(X_train_mms, y_train)

y_pred_dt3 = model_dt3.predict(X_test_mms)

In [91]:
print(classification_report(y_test, y_pred_dt3))

              precision    recall  f1-score   support

           0       0.83      0.81      0.82      1038
           1       0.50      0.53      0.51       369

    accuracy                           0.74      1407
   macro avg       0.66      0.67      0.67      1407
weighted avg       0.74      0.74      0.74      1407

In [ ]:
!pip install imbalanced-learn

## SMOTEENN () [UpSampling + ENN)

In [92]:
from imblearn.combine import SMOTEENN

In [93]:
sm = SMOTEENN()
X_train_resampled, y_train_resampled = sm.fit_resample(X_train, y_train)

In [94]:
model_dt_smoteenn = DecisionTreeClassifier()
model_dt_smoteenn.fit(X_train_resampled, y_train_resampled)

y_pred_dt_smoteenn = model_dt_smoteenn.predict(X_test)

In [95]:
print(classification_report(y_test, y_pred_dt_smoteenn))

              precision    recall  f1-score   support

           0       0.90      0.69      0.78      1038
           1       0.47      0.78      0.59       369

    accuracy                           0.71      1407
   macro avg       0.69      0.73      0.69      1407
weighted avg       0.79      0.71      0.73      1407

In [96]:
model_rf_smoteenn = RandomForestClassifier(n_estimators=500)
model_rf_smoteenn.fit(X_train_resampled, y_train_resampled)

y_pred_rf_smoteenn = model_rf_smoteenn.predict(X_test)

In [97]:
print(classification_report(y_test, y_pred_rf_smoteenn))

              precision    recall  f1-score   support

           0       0.91      0.70      0.79      1038
           1       0.49      0.80      0.61       369

    accuracy                           0.73      1407
   macro avg       0.70      0.75      0.70      1407
weighted avg       0.80      0.73      0.74      1407

In [99]:
!pip install xgboost

Collecting xgboost
  Downloading xgboost-3.2.0-py3-none-win_amd64.whl.metadata (2.1 kB)
Requirement already satisfied: numpy in c:\users\dell\ac\envs\agentic-2-base\lib\site-packages (from xgboost) (2.2.6)
Requirement already satisfied: scipy in c:\users\dell\ac\envs\agentic-2-base\lib\site-packages (from xgboost) (1.15.3)
Downloading xgboost-3.2.0-py3-none-win_amd64.whl (101.7 MB)
   ---------------------------------------- 0.0/101.7 MB ? eta -:--:--
   ---------------------------------------- 1.0/101.7 MB 5.0 MB/s eta 0:00:20
    --------------------------------------- 1.8/101.7 MB 4.6 MB/s eta 0:00:22
   - -------------------------------------- 2.9/101.7 MB 4.3 MB/s eta 0:00:23
   - -------------------------------------- 3.4/101.7 MB 4.1 MB/s eta 0:00:24
   - -------------------------------------- 4.5/101.7 MB 4.1 MB/s eta 0:00:24
   -- ------------------------------------- 5.2/101.7 MB 4.0 MB/s eta 0:00:24
   -- ------------------------------------- 6.0/101.7 MB 4.0 MB/s eta 0:00:24
   -- ------------------------------------- 7.1/101.7 MB 4.0 MB/s eta 0:00:24
   -- ------------------------------------- 7.6/101.7 MB 4.0 MB/s eta 0:00:24
   --- ------------------------------------ 8.7/101.7 MB 4.0 MB/s eta 0:00:24
   --- ------------------------------------ 9.4/101.7 MB 4.0 MB/s eta 0:00:24
   ---- ----------------------------------- 10.5/101.7 MB 4.0 MB/s eta 0:00:23
   ---- ----------------------------------- 11.3/101.7 MB 4.0 MB/s eta 0:00:23
   ---- ----------------------------------- 11.8/101.7 MB 3.9 MB/s eta 0:00:24
   ----- ---------------------------------- 12.8/101.7 MB 3.9 MB/s eta 0:00:23
   ----- ---------------------------------- 13.6/101.7 MB 3.9 MB/s eta 0:00:23
   ----- ---------------------------------- 14.4/101.7 MB 3.9 MB/s eta 0:00:23
   ------ --------------------------------- 15.5/101.7 MB 3.9 MB/s eta 0:00:22
   ------ --------------------------------- 16.3/101.7 MB 3.9 MB/s eta 0:00:22
   ------ --------------------------------- 17.0/101.7 MB 3.9 MB/s eta 0:00:22
   ------- -------------------------------- 17.8/101.7 MB 3.9 MB/s eta 0:00:22
   ------- -------------------------------- 18.9/101.7 MB 3.9 MB/s eta 0:00:22
   ------- -------------------------------- 19.7/101.7 MB 3.9 MB/s eta 0:00:21
   -------- ------------------------------- 20.4/101.7 MB 3.9 MB/s eta 0:00:21
   -------- ------------------------------- 21.2/101.7 MB 3.9 MB/s eta 0:00:21
   -------- ------------------------------- 22.0/101.7 MB 3.9 MB/s eta 0:00:21
   -------- ------------------------------- 22.8/101.7 MB 3.9 MB/s eta 0:00:21
   --------- ------------------------------ 23.9/101.7 MB 3.9 MB/s eta 0:00:20
   --------- ------------------------------ 24.9/101.7 MB 3.9 MB/s eta 0:00:20
   ---------- ----------------------------- 25.4/101.7 MB 3.9 MB/s eta 0:00:20
   ---------- ----------------------------- 26.5/101.7 MB 3.9 MB/s eta 0:00:20
   ---------- ----------------------------- 27.3/101.7 MB 3.9 MB/s eta 0:00:20
   ----------- ---------------------------- 28.0/101.7 MB 3.9 MB/s eta 0:00:20
   ----------- ---------------------------- 29.1/101.7 MB 3.9 MB/s eta 0:00:19
   ----------- ---------------------------- 29.9/101.7 MB 3.9 MB/s eta 0:00:19
   ------------ --------------------------- 30.9/101.7 MB 3.9 MB/s eta 0:00:19
   ------------ --------------------------- 31.7/101.7 MB 3.9 MB/s eta 0:00:18
   ------------ --------------------------- 32.8/101.7 MB 3.9 MB/s eta 0:00:18
   ------------- -------------------------- 33.3/101.7 MB 3.9 MB/s eta 0:00:18
   ------------- -------------------------- 34.3/101.7 MB 3.9 MB/s eta 0:00:18
   ------------- -------------------------- 35.4/101.7 MB 3.9 MB/s eta 0:00:17
   -------------- ------------------------- 35.9/101.7 MB 3.9 MB/s eta 0:00:17
   -------------- ------------------------- 37.0/101.7 MB 3.9 MB/s eta 0:00:17
   -------------- ------------------------- 37.7/101.7 MB 3.9 MB/s eta 0:00:17
   --------------- ------------------------ 38.3/101.7 MB 3.9 MB/s eta 0:00:17
   --------------- ------------------------ 39.3/101.7 MB 3.9 MB/s eta 0:00:17
   --------------- ------------------------ 40.4/101.7 MB 3.9 MB/s eta 0:00:16
   ---------------- ----------------------- 41.2/101.7 MB 3.9 MB/s eta 0:00:16
   ---------------- ----------------------- 41.9/101.7 MB 3.9 MB/s eta 0:00:16
   ---------------- ----------------------- 43.0/101.7 MB 3.9 MB/s eta 0:00:16
   ----------------- ---------------------- 43.8/101.7 MB 3.9 MB/s eta 0:00:15
   ----------------- ---------------------- 44.6/101.7 MB 3.9 MB/s eta 0:00:15
   ----------------- ---------------------- 45.4/101.7 MB 3.9 MB/s eta 0:00:15
   ------------------ --------------------- 46.4/101.7 MB 3.9 MB/s eta 0:00:15
   ------------------ --------------------- 47.2/101.7 MB 3.9 MB/s eta 0:00:14
   ------------------ --------------------- 48.0/101.7 MB 3.9 MB/s eta 0:00:14
   ------------------- -------------------- 48.8/101.7 MB 3.9 MB/s eta 0:00:14
   ------------------- -------------------- 49.5/101.7 MB 3.9 MB/s eta 0:00:14
   ------------------- -------------------- 50.6/101.7 MB 3.9 MB/s eta 0:00:14
   -------------------- ------------------- 51.4/101.7 MB 3.9 MB/s eta 0:00:13
   -------------------- ------------------- 52.2/101.7 MB 3.9 MB/s eta 0:00:13
   -------------------- ------------------- 53.0/101.7 MB 3.9 MB/s eta 0:00:13
   --------------------- ------------------ 54.0/101.7 MB 3.9 MB/s eta 0:00:13
   --------------------- ------------------ 54.8/101.7 MB 3.9 MB/s eta 0:00:13
   --------------------- ------------------ 55.6/101.7 MB 3.9 MB/s eta 0:00:12
   ---------------------- ----------------- 56.4/101.7 MB 3.9 MB/s eta 0:00:12
   ---------------------- ----------------- 57.4/101.7 MB 3.9 MB/s eta 0:00:12
   ---------------------- ----------------- 58.2/101.7 MB 3.9 MB/s eta 0:00:12
   ----------------------- ---------------- 59.0/101.7 MB 3.9 MB/s eta 0:00:11
   ----------------------- ---------------- 59.8/101.7 MB 3.9 MB/s eta 0:00:11
   ----------------------- ---------------- 60.6/101.7 MB 3.9 MB/s eta 0:00:11
   ------------------------ --------------- 61.3/101.7 MB 3.9 MB/s eta 0:00:11
   ------------------------ --------------- 62.4/101.7 MB 3.9 MB/s eta 0:00:11
   ------------------------ --------------- 63.2/101.7 MB 3.9 MB/s eta 0:00:10
   ------------------------- -------------- 64.0/101.7 MB 3.9 MB/s eta 0:00:10
   ------------------------- -------------- 65.0/101.7 MB 3.9 MB/s eta 0:00:10
   ------------------------- -------------- 65.5/101.7 MB 3.9 MB/s eta 0:00:10
   -------------------------- ------------- 66.6/101.7 MB 3.9 MB/s eta 0:00:10
   -------------------------- ------------- 67.6/101.7 MB 3.9 MB/s eta 0:00:09
   -------------------------- ------------- 68.4/101.7 MB 3.9 MB/s eta 0:00:09
   --------------------------- ------------ 69.2/101.7 MB 3.9 MB/s eta 0:00:09
   --------------------------- ------------ 70.0/101.7 MB 3.9 MB/s eta 0:00:09
   --------------------------- ------------ 70.8/101.7 MB 3.9 MB/s eta 0:00:08
   ---------------------------- ----------- 71.8/101.7 MB 3.9 MB/s eta 0:00:08
   ---------------------------- ----------- 72.6/101.7 MB 3.9 MB/s eta 0:00:08
   ---------------------------- ----------- 73.4/101.7 MB 3.9 MB/s eta 0:00:08
   ----------------------------- ---------- 74.2/101.7 MB 3.9 MB/s eta 0:00:08
   ----------------------------- ---------- 75.2/101.7 MB 3.9 MB/s eta 0:00:07
   ----------------------------- ---------- 76.0/101.7 MB 3.9 MB/s eta 0:00:07
   ------------------------------ --------- 76.8/101.7 MB 3.9 MB/s eta 0:00:07
   ------------------------------ --------- 77.6/101.7 MB 3.9 MB/s eta 0:00:07
   ------------------------------ --------- 78.6/101.7 MB 3.9 MB/s eta 0:00:06
   ------------------------------- -------- 79.4/101.7 MB 3.9 MB/s eta 0:00:06
   ------------------------------- -------- 80.2/101.7 MB 3.9 MB/s eta 0:00:06
   ------------------------------- -------- 81.0/101.7 MB 3.9 MB/s eta 0:00:06
   -------------------------------- ------- 81.8/101.7 MB 3.9 MB/s eta 0:00:06
   -------------------------------- ------- 82.6/101.7 MB 3.9 MB/s eta 0:00:05
   -------------------------------- ------- 83.4/101.7 MB 3.9 MB/s eta 0:00:05
   --------------------------------- ------ 84.1/101.7 MB 3.9 MB/s eta 0:00:05
   --------------------------------- ------ 85.2/101.7 MB 3.9 MB/s eta 0:00:05
   --------------------------------- ------ 86.0/101.7 MB 3.9 MB/s eta 0:00:05
   ---------------------------------- ----- 86.8/101.7 MB 3.9 MB/s eta 0:00:04
   ---------------------------------- ----- 87.6/101.7 MB 3.9 MB/s eta 0:00:04
   ---------------------------------- ----- 88.3/101.7 MB 3.9 MB/s eta 0:00:04
   ----------------------------------- ---- 89.4/101.7 MB 3.9 MB/s eta 0:00:04
   ----------------------------------- ---- 90.2/101.7 MB 3.9 MB/s eta 0:00:03
   ----------------------------------- ---- 91.0/101.7 MB 3.9 MB/s eta 0:00:03
   ------------------------------------ --- 91.8/101.7 MB 3.9 MB/s eta 0:00:03
   ------------------------------------ --- 92.8/101.7 MB 3.9 MB/s eta 0:00:03
   ------------------------------------ --- 93.6/101.7 MB 3.9 MB/s eta 0:00:03
   ------------------------------------- -- 94.4/101.7 MB 3.9 MB/s eta 0:00:02
   ------------------------------------- -- 95.2/101.7 MB 3.9 MB/s eta 0:00:02
   ------------------------------------- -- 96.2/101.7 MB 3.9 MB/s eta 0:00:02
   -------------------------------------- - 97.0/101.7 MB 3.9 MB/s eta 0:00:02
   -------------------------------------- - 97.8/101.7 MB 3.9 MB/s eta 0:00:02
   -------------------------------------- - 98.6/101.7 MB 3.9 MB/s eta 0:00:01
   ---------------------------------------  99.4/101.7 MB 3.9 MB/s eta 0:00:01
   ---------------------------------------  100.4/101.7 MB 3.9 MB/s eta 0:00:01
   ---------------------------------------  101.2/101.7 MB 3.9 MB/s eta 0:00:01
   ---------------------------------------  101.4/101.7 MB 3.9 MB/s eta 0:00:01
   ---------------------------------------  101.4/101.7 MB 3.9 MB/s eta 0:00:01
   ---------------------------------------- 101.7/101.7 MB 3.8 MB/s eta 0:00:00
Installing collected packages: xgboost
Successfully installed xgboost-3.2.0

## XGBoost without SMOTEENN

In [100]:
from xgboost import XGBClassifier

# Initialize and train the XGBoost model
model_xgb = XGBClassifier(random_state=42)  # random_state for reproducibility
model_xgb.fit(X_train, y_train)

# Make predictions on the test set
y_pred_xgb = model_xgb.predict(X_test)

In [101]:
print(classification_report(y_test, y_pred_xgb))

              precision    recall  f1-score   support

           0       0.84      0.88      0.86      1038
           1       0.61      0.53      0.57       369

    accuracy                           0.79      1407
   macro avg       0.73      0.70      0.71      1407
weighted avg       0.78      0.79      0.78      1407

## XGBoost with SMOTEENN

In [102]:
from xgboost import XGBClassifier

# Initialize and train the XGBoost model
model_xgb_smoteenn = XGBClassifier(random_state=42)  # random_state for reproducibility
model_xgb_smoteenn.fit(X_train_resampled, y_train_resampled)

# Make predictions on the test set
y_pred_xgb_smoteenn = model_xgb_smoteenn.predict(X_test)

In [103]:
print(classification_report(y_test, y_pred_xgb_smoteenn))

              precision    recall  f1-score   support

           0       0.90      0.71      0.79      1038
           1       0.49      0.79      0.60       369

    accuracy                           0.73      1407
   macro avg       0.70      0.75      0.70      1407
weighted avg       0.79      0.73      0.74      1407

## XGBoost with SMOTE

In [104]:
from imblearn.over_sampling import SMOTE
from xgboost import XGBClassifier
from collections import Counter

# Check class distribution before SMOTE
print("Before SMOTE:", Counter(y_train))

# Apply SMOTE to the training data only
smote = SMOTE(random_state=42)
X_train_smote, y_train_smote = smote.fit_resample(X_train, y_train)

# Check class distribution after SMOTE
print("After SMOTE:", Counter(y_train_smote))

# Initialize and train the XGBoost model on resampled data
model_xgb_smote = XGBClassifier(random_state=42)
model_xgb_smote.fit(X_train_smote, y_train_smote)

# Make predictions on the original test set (unchanged)
y_pred_xgb_smote = model_xgb_smote.predict(X_test)

Before SMOTE: Counter({0: 4125, 1: 1500})
After SMOTE: Counter({0: 4125, 1: 4125})

In [105]:
print(classification_report(y_test, y_pred_xgb_smote))

              precision    recall  f1-score   support

           0       0.86      0.85      0.85      1038
           1       0.59      0.59      0.59       369

    accuracy                           0.78      1407
   macro avg       0.72      0.72      0.72      1407
weighted avg       0.79      0.78      0.78      1407

In [106]:
from imblearn.over_sampling import ADASYN
from xgboost import XGBClassifier
from collections import Counter 

# Check original distribution
print("Before ADASYN:", Counter(y_train))

# Apply ADASYN to training data only
adasyn = ADASYN(random_state=42)
X_train_adasyn, y_train_adasyn = adasyn.fit_resample(X_train, y_train)

# Check new distribution
print("After ADASYN:", Counter(y_train_adasyn))

# Train XGBoost on ADASYN-resampled data
model_xgb_adasyn = XGBClassifier(random_state=42)
model_xgb_adasyn.fit(X_train_adasyn, y_train_adasyn)

# Predict on the original test set
y_pred_xgb_adasyn = model_xgb_adasyn.predict(X_test)

# Evaluate
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

print("Accuracy:", accuracy_score(y_test, y_pred_xgb_adasyn))
print("\nClassification Report:\n", classification_report(y_test, y_pred_xgb_adasyn))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred_xgb_adasyn))

Before ADASYN: Counter({0: 4125, 1: 1500})
After ADASYN: Counter({0: 4125, 1: 4087})
Accuracy: 0.7839374555792467

Classification Report:
               precision    recall  f1-score   support

           0       0.86      0.85      0.85      1038
           1       0.59      0.60      0.59       369

    accuracy                           0.78      1407
   macro avg       0.72      0.72      0.72      1407
weighted avg       0.79      0.78      0.78      1407


Confusion Matrix:
 [[882 156]
 [148 221]]

In [107]:
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Calculate scale_pos_weight (ratio of negative to positive class)
scale_pos_weight = (y_train == 0).sum() / (y_train == 1).sum()
print(f"scale_pos_weight: {scale_pos_weight:.2f}")

# Train XGBoost with scale_pos_weight
model_xgb_weighted = XGBClassifier(
    scale_pos_weight=scale_pos_weight,
    random_state=42,
    eval_metric='logloss'  # avoids warnings
)

model_xgb_weighted.fit(X_train, y_train)
y_pred_weighted = model_xgb_weighted.predict(X_test)

# Evaluate
print("Accuracy:", accuracy_score(y_test, y_pred_weighted))
print("\nClassification Report:\n", classification_report(y_test, y_pred_weighted))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred_weighted))

scale_pos_weight: 2.75
Accuracy: 0.7526652452025586

Classification Report:
               precision    recall  f1-score   support

           0       0.88      0.78      0.82      1038
           1       0.52      0.69      0.59       369

    accuracy                           0.75      1407
   macro avg       0.70      0.73      0.71      1407
weighted avg       0.78      0.75      0.76      1407


Confusion Matrix:
 [[805 233]
 [115 254]]

In [108]:
from sklearn.ensemble import AdaBoostClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import numpy as np

# Calculate the weight for the positive (minority) class
# Common approach: weight_positive = negative_count / positive_count
negative_count = (y_train == 0).sum()
positive_count = (y_train == 1).sum()
weight_positive = negative_count / positive_count if positive_count > 0 else 1
print(f"Negative class count: {negative_count}")
print(f"Positive class count: {positive_count}")
print(f"Weight for positive class: {weight_positive:.2f}")

# Create sample weights: higher weight for minority class
sample_weight = np.where(y_train == 1, weight_positive, 1.0)

# Train AdaBoost with sample weights
model_ada_weighted = AdaBoostClassifier(
    n_estimators=50,  # default, you can tune
    random_state=42
)

model_ada_weighted.fit(X_train, y_train, sample_weight=sample_weight)

# Predict and evaluate
y_pred_ada_weighted = model_ada_weighted.predict(X_test)

print("AdaBoost with sample weighting - Accuracy:", accuracy_score(y_test, y_pred_ada_weighted))
print("\nClassification Report:\n", classification_report(y_test, y_pred_ada_weighted))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred_ada_weighted))

Negative class count: 4125
Positive class count: 1500
Weight for positive class: 2.75
AdaBoost with sample weighting - Accuracy: 0.7420042643923241

Classification Report:
               precision    recall  f1-score   support

           0       0.91      0.72      0.80      1038
           1       0.51      0.81      0.62       369

    accuracy                           0.74      1407
   macro avg       0.71      0.76      0.71      1407
weighted avg       0.81      0.74      0.76      1407


Confusion Matrix:
 [[745 293]
 [ 70 299]]

## **Hyper Parameter Optimization**

In [109]:
from sklearn.model_selection import RandomizedSearchCV
from xgboost import XGBClassifier

param_grid = {
    'max_depth': [3, 4, 5, 6, 7],
    'learning_rate': [0.01, 0.05, 0.1, 0.2],
    'n_estimators': [100, 200, 300, 400],
    'subsample': [0.7, 0.8, 0.9, 1.0],
    'colsample_bytree': [0.7, 0.8, 0.9, 1.0],
    'min_child_weight': [1, 3, 5],
    'gamma': [0, 0.1, 0.2],
    'scale_pos_weight': [1, scale_pos_weight]  # try both balanced and weighted
}

xgb = XGBClassifier(random_state=42, eval_metric='logloss')

# Use 'f1' or 'recall' scoring since churn is imbalanced
search = RandomizedSearchCV(
    xgb,
    param_grid,
    n_iter=50,
    cv=5,
    scoring='f1',  # or 'recall' if catching churn is priority
    random_state=42,
    n_jobs=-1
)

search.fit(X_train, y_train)

print("Best parameters:", search.best_params_)
print("Best CV F1 score:", search.best_score_)

# Use best model
best_model = search.best_estimator_
y_pred_best = best_model.predict(X_test)
print("\nTest Classification Report:\n", classification_report(y_test, y_pred_best))

Best parameters: {'subsample': 0.7, 'scale_pos_weight': np.float64(2.75), 'n_estimators': 400, 'min_child_weight': 3, 'max_depth': 7, 'learning_rate': 0.01, 'gamma': 0, 'colsample_bytree': 0.9}
Best CV F1 score: 0.6302834629470799

Test Classification Report:
               precision    recall  f1-score   support

           0       0.90      0.76      0.82      1038
           1       0.53      0.76      0.62       369

    accuracy                           0.76      1407
   macro avg       0.71      0.76      0.72      1407
weighted avg       0.80      0.76      0.77      1407

In [110]:
# Save this model

import joblib

# Save the best model to a .pkl file
joblib.dump(best_model, 'best_xgboost_churn_model.pkl')

print("Best model successfully saved as 'best_xgboost_churn_model.pkl'")

Best model successfully saved as 'best_xgboost_churn_model.pkl'

## Trying out few more techniques

In [111]:
from sklearn.ensemble import RandomForestClassifier

model_rf = RandomForestClassifier(
    class_weight='balanced',
    random_state=42,
    n_estimators=300,
    max_depth=6
)
model_rf.fit(X_train, y_train)
y_pred_rf = model_rf.predict(X_test)
print(classification_report(y_test, y_pred_rf))

              precision    recall  f1-score   support

           0       0.91      0.71      0.80      1038
           1       0.50      0.80      0.61       369

    accuracy                           0.73      1407
   macro avg       0.70      0.76      0.70      1407
weighted avg       0.80      0.73      0.75      1407

In [113]:
!pip install catboost

Collecting catboost
  Downloading catboost-1.2.10-cp311-cp311-win_amd64.whl.metadata (1.5 kB)
Collecting graphviz (from catboost)
  Using cached graphviz-0.21-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: matplotlib in c:\users\dell\ac\envs\agentic-2-base\lib\site-packages (from catboost) (3.11.2)
Requirement already satisfied: numpy<3.0,>=1.16.0 in c:\users\dell\ac\envs\agentic-2-base\lib\site-packages (from catboost) (2.2.6)
Requirement already satisfied: pandas<4.0,>=0.24 in c:\users\dell\ac\envs\agentic-2-base\lib\site-packages (from catboost) (2.2.3)
Requirement already satisfied: scipy in c:\users\dell\ac\envs\agentic-2-base\lib\site-packages (from catboost) (1.15.3)
Collecting plotly (from catboost)
  Downloading plotly-7.1.0-py3-none-any.whl.metadata (8.8 kB)
Requirement already satisfied: six in c:\users\dell\ac\envs\agentic-2-base\lib\site-packages (from catboost) (1.17.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\dell\ac\envs\agentic-2-base\lib\site-packages (from pandas<4.0,>=0.24->catboost) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\dell\ac\envs\agentic-2-base\lib\site-packages (from pandas<4.0,>=0.24->catboost) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\dell\ac\envs\agentic-2-base\lib\site-packages (from pandas<4.0,>=0.24->catboost) (2025.2)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\dell\ac\envs\agentic-2-base\lib\site-packages (from matplotlib->catboost) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\users\dell\ac\envs\agentic-2-base\lib\site-packages (from matplotlib->catboost) (0.12.1)
Requirement already satisfied: fonttools>=4.28.2 in c:\users\dell\ac\envs\agentic-2-base\lib\site-packages (from matplotlib->catboost) (4.67.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\dell\ac\envs\agentic-2-base\lib\site-packages (from matplotlib->catboost) (1.5.1)
Requirement already satisfied: packaging>=20.0 in c:\users\dell\ac\envs\agentic-2-base\lib\site-packages (from matplotlib->catboost) (24.2)
Requirement already satisfied: pillow>=9 in c:\users\dell\ac\envs\agentic-2-base\lib\site-packages (from matplotlib->catboost) (11.2.1)
Requirement already satisfied: pyparsing>=3 in c:\users\dell\ac\envs\agentic-2-base\lib\site-packages (from matplotlib->catboost) (3.2.3)
Collecting narwhals>=1.15.1 (from plotly->catboost)
  Using cached narwhals-2.27.1-py3-none-any.whl.metadata (15 kB)
Downloading catboost-1.2.10-cp311-cp311-win_amd64.whl (100.2 MB)
   ---------------------------------------- 0.0/100.2 MB ? eta -:--:--
   ---------------------------------------- 0.0/100.2 MB ? eta -:--:--
   ---------------------------------------- 0.0/100.2 MB ? eta -:--:--
   ---------------------------------------- 0.0/100.2 MB ? eta -:--:--
   ---------------------------------------- 1.0/100.2 MB 4.6 MB/s eta 0:00:22
    --------------------------------------- 1.8/100.2 MB 4.8 MB/s eta 0:00:21
   - -------------------------------------- 2.6/100.2 MB 4.3 MB/s eta 0:00:23
   - -------------------------------------- 3.7/100.2 MB 4.3 MB/s eta 0:00:23
   - -------------------------------------- 4.5/100.2 MB 4.2 MB/s eta 0:00:23
   -- ------------------------------------- 5.2/100.2 MB 4.1 MB/s eta 0:00:23
   -- ------------------------------------- 6.0/100.2 MB 4.1 MB/s eta 0:00:24
   -- ------------------------------------- 7.1/100.2 MB 4.1 MB/s eta 0:00:23
   --- ------------------------------------ 7.9/100.2 MB 4.0 MB/s eta 0:00:23
   --- ------------------------------------ 8.7/100.2 MB 3.9 MB/s eta 0:00:24
   --- ------------------------------------ 9.2/100.2 MB 3.8 MB/s eta 0:00:24
   --- ------------------------------------ 10.0/100.2 MB 3.8 MB/s eta 0:00:24
   ---- ----------------------------------- 11.0/100.2 MB 3.9 MB/s eta 0:00:24
   ---- ----------------------------------- 11.8/100.2 MB 3.9 MB/s eta 0:00:23
   ----- ---------------------------------- 12.6/100.2 MB 3.8 MB/s eta 0:00:24
   ----- ---------------------------------- 12.6/100.2 MB 3.8 MB/s eta 0:00:24
   ----- ---------------------------------- 12.6/100.2 MB 3.8 MB/s eta 0:00:24
   ----- ---------------------------------- 12.6/100.2 MB 3.8 MB/s eta 0:00:24
   ----- ---------------------------------- 12.6/100.2 MB 3.8 MB/s eta 0:00:24
   ----- ---------------------------------- 12.6/100.2 MB 3.8 MB/s eta 0:00:24
   ----- ---------------------------------- 12.6/100.2 MB 3.8 MB/s eta 0:00:24
   ----- ---------------------------------- 12.6/100.2 MB 3.8 MB/s eta 0:00:24
   ----- ---------------------------------- 12.6/100.2 MB 3.8 MB/s eta 0:00:24
   ----- ---------------------------------- 12.6/100.2 MB 3.8 MB/s eta 0:00:24
   ----- ---------------------------------- 12.6/100.2 MB 3.8 MB/s eta 0:00:24
   ----- ---------------------------------- 12.6/100.2 MB 3.8 MB/s eta 0:00:24
   ----- ---------------------------------- 12.6/100.2 MB 3.8 MB/s eta 0:00:24
   ----- ---------------------------------- 12.6/100.2 MB 3.8 MB/s eta 0:00:24
   ----- ---------------------------------- 12.6/100.2 MB 3.8 MB/s eta 0:00:24
   ----- ---------------------------------- 12.6/100.2 MB 3.8 MB/s eta 0:00:24
   ----- ---------------------------------- 12.8/100.2 MB 1.9 MB/s eta 0:00:47
   ----- ---------------------------------- 12.8/100.2 MB 1.9 MB/s eta 0:00:47
   ----- ---------------------------------- 12.8/100.2 MB 1.9 MB/s eta 0:00:47
   ----- ---------------------------------- 12.8/100.2 MB 1.9 MB/s eta 0:00:47
   ----- ---------------------------------- 12.8/100.2 MB 1.9 MB/s eta 0:00:47
   ----- ---------------------------------- 12.8/100.2 MB 1.9 MB/s eta 0:00:47
   ----- ---------------------------------- 12.8/100.2 MB 1.9 MB/s eta 0:00:47
   ----- ---------------------------------- 12.8/100.2 MB 1.9 MB/s eta 0:00:47
   ----- ---------------------------------- 12.8/100.2 MB 1.9 MB/s eta 0:00:47
   ----- ---------------------------------- 12.8/100.2 MB 1.9 MB/s eta 0:00:47
   ----- ---------------------------------- 12.8/100.2 MB 1.9 MB/s eta 0:00:47
   ----- ---------------------------------- 12.8/100.2 MB 1.9 MB/s eta 0:00:47
   ----- ---------------------------------- 12.8/100.2 MB 1.9 MB/s eta 0:00:47
   ----- ---------------------------------- 12.8/100.2 MB 1.9 MB/s eta 0:00:47
   ----- ---------------------------------- 12.8/100.2 MB 1.9 MB/s eta 0:00:47
   ----- ---------------------------------- 12.8/100.2 MB 1.9 MB/s eta 0:00:47
   ----- ---------------------------------- 12.8/100.2 MB 1.9 MB/s eta 0:00:47
   ----- ---------------------------------- 12.8/100.2 MB 1.9 MB/s eta 0:00:47
   ----- ---------------------------------- 12.8/100.2 MB 1.9 MB/s eta 0:00:47
   ----- ---------------------------------- 12.8/100.2 MB 1.9 MB/s eta 0:00:47
   ----- ---------------------------------- 12.8/100.2 MB 1.9 MB/s eta 0:00:47
   ----- ---------------------------------- 12.8/100.2 MB 1.9 MB/s eta 0:00:47
   ----- ---------------------------------- 12.8/100.2 MB 1.9 MB/s eta 0:00:47
   ----- ---------------------------------- 12.8/100.2 MB 1.9 MB/s eta 0:00:47
   ----- ---------------------------------- 12.8/100.2 MB 1.9 MB/s eta 0:00:47
   ----- ---------------------------------- 12.8/100.2 MB 1.9 MB/s eta 0:00:47
   ----- ---------------------------------- 12.8/100.2 MB 1.9 MB/s eta 0:00:47
   ----- ---------------------------------- 12.8/100.2 MB 1.9 MB/s eta 0:00:47
   ----- ---------------------------------- 12.8/100.2 MB 1.9 MB/s eta 0:00:47
   ----- ---------------------------------- 12.8/100.2 MB 1.9 MB/s eta 0:00:47
   ----- ---------------------------------- 12.8/100.2 MB 1.9 MB/s eta 0:00:47
   ----- ---------------------------------- 12.8/100.2 MB 1.9 MB/s eta 0:00:47
   ----- ---------------------------------- 12.8/100.2 MB 1.9 MB/s eta 0:00:47
   ----- ---------------------------------- 12.8/100.2 MB 1.9 MB/s eta 0:00:47
   ----- ---------------------------------- 12.8/100.2 MB 1.9 MB/s eta 0:00:47
   ----- --------------------------------- 13.1/100.2 MB 891.6 kB/s eta 0:01:38
   ----- --------------------------------- 14.4/100.2 MB 964.8 kB/s eta 0:01:29
   ------ --------------------------------- 15.2/100.2 MB 1.0 MB/s eta 0:01:25
   ------ --------------------------------- 16.0/100.2 MB 1.0 MB/s eta 0:01:21
   ------ --------------------------------- 16.3/100.2 MB 1.1 MB/s eta 0:01:20
   ------ --------------------------------- 16.3/100.2 MB 1.1 MB/s eta 0:01:20
   ------ --------------------------------- 16.3/100.2 MB 1.1 MB/s eta 0:01:20
   ------ --------------------------------- 16.3/100.2 MB 1.1 MB/s eta 0:01:20
   ------ --------------------------------- 16.3/100.2 MB 1.1 MB/s eta 0:01:20
   ------ -------------------------------- 16.5/100.2 MB 989.7 kB/s eta 0:01:25
   ------- -------------------------------- 17.6/100.2 MB 1.0 MB/s eta 0:01:20
   ------- -------------------------------- 18.4/100.2 MB 1.1 MB/s eta 0:01:17
   ------- -------------------------------- 19.4/100.2 MB 1.1 MB/s eta 0:01:13
   -------- ------------------------------- 20.2/100.2 MB 1.2 MB/s eta 0:01:10
   -------- ------------------------------- 21.0/100.2 MB 1.2 MB/s eta 0:01:07
   -------- ------------------------------- 21.8/100.2 MB 1.2 MB/s eta 0:01:05
   -------- ------------------------------- 22.5/100.2 MB 1.2 MB/s eta 0:01:03
   --------- ------------------------------ 23.3/100.2 MB 1.3 MB/s eta 0:01:01
   --------- ------------------------------ 24.4/100.2 MB 1.3 MB/s eta 0:00:58
   ---------- ----------------------------- 25.2/100.2 MB 1.3 MB/s eta 0:00:57
   ---------- ----------------------------- 26.0/100.2 MB 1.4 MB/s eta 0:00:55
   ---------- ----------------------------- 26.7/100.2 MB 1.4 MB/s eta 0:00:53
   ----------- ---------------------------- 27.8/100.2 MB 1.4 MB/s eta 0:00:51
   ----------- ---------------------------- 28.6/100.2 MB 1.5 MB/s eta 0:00:50
   ----------- ---------------------------- 29.4/100.2 MB 1.5 MB/s eta 0:00:48
   ------------ --------------------------- 30.1/100.2 MB 1.5 MB/s eta 0:00:47
   ------------ --------------------------- 30.9/100.2 MB 1.5 MB/s eta 0:00:46
   ------------ --------------------------- 32.0/100.2 MB 1.6 MB/s eta 0:00:44
   ------------- -------------------------- 32.8/100.2 MB 1.6 MB/s eta 0:00:43
   ------------- -------------------------- 33.6/100.2 MB 1.6 MB/s eta 0:00:42
   ------------- -------------------------- 34.3/100.2 MB 1.6 MB/s eta 0:00:41
   -------------- ------------------------- 35.1/100.2 MB 1.6 MB/s eta 0:00:40
   -------------- ------------------------- 36.2/100.2 MB 1.7 MB/s eta 0:00:39
   -------------- ------------------------- 37.0/100.2 MB 1.7 MB/s eta 0:00:38
   --------------- ------------------------ 37.7/100.2 MB 1.7 MB/s eta 0:00:37
   --------------- ------------------------ 38.5/100.2 MB 1.7 MB/s eta 0:00:36
   --------------- ------------------------ 39.3/100.2 MB 1.8 MB/s eta 0:00:35
   ---------------- ----------------------- 40.4/100.2 MB 1.8 MB/s eta 0:00:34
   ---------------- ----------------------- 41.2/100.2 MB 1.8 MB/s eta 0:00:33
   ---------------- ----------------------- 41.9/100.2 MB 1.8 MB/s eta 0:00:33
   ----------------- ---------------------- 42.7/100.2 MB 1.8 MB/s eta 0:00:32
   ----------------- ---------------------- 43.8/100.2 MB 1.9 MB/s eta 0:00:31
   ----------------- ---------------------- 44.6/100.2 MB 1.9 MB/s eta 0:00:30
   ------------------ --------------------- 45.4/100.2 MB 1.9 MB/s eta 0:00:29
   ------------------ --------------------- 46.1/100.2 MB 1.9 MB/s eta 0:00:29
   ------------------ --------------------- 46.9/100.2 MB 1.9 MB/s eta 0:00:28
   ------------------- -------------------- 48.0/100.2 MB 1.9 MB/s eta 0:00:27
   ------------------- -------------------- 48.8/100.2 MB 2.0 MB/s eta 0:00:27
   ------------------- -------------------- 49.5/100.2 MB 2.0 MB/s eta 0:00:26
   -------------------- ------------------- 50.3/100.2 MB 2.0 MB/s eta 0:00:25
   -------------------- ------------------- 51.1/100.2 MB 2.0 MB/s eta 0:00:25
   -------------------- ------------------- 52.2/100.2 MB 2.0 MB/s eta 0:00:24
   --------------------- ------------------ 53.0/100.2 MB 2.0 MB/s eta 0:00:24
   --------------------- ------------------ 53.7/100.2 MB 2.1 MB/s eta 0:00:23
   --------------------- ------------------ 53.7/100.2 MB 2.1 MB/s eta 0:00:23
   --------------------- ------------------ 53.7/100.2 MB 2.1 MB/s eta 0:00:23
   --------------------- ------------------ 53.7/100.2 MB 2.1 MB/s eta 0:00:23
   --------------------- ------------------ 53.7/100.2 MB 2.1 MB/s eta 0:00:23
   --------------------- ------------------ 54.5/100.2 MB 2.0 MB/s eta 0:00:23
   ---------------------- ----------------- 55.6/100.2 MB 2.0 MB/s eta 0:00:23
   ---------------------- ----------------- 56.4/100.2 MB 2.0 MB/s eta 0:00:22
   ---------------------- ----------------- 57.4/100.2 MB 2.1 MB/s eta 0:00:21
   ----------------------- ---------------- 58.2/100.2 MB 2.1 MB/s eta 0:00:21
   ----------------------- ---------------- 59.0/100.2 MB 2.1 MB/s eta 0:00:20
   ----------------------- ---------------- 59.8/100.2 MB 2.1 MB/s eta 0:00:20
   ------------------------ --------------- 60.8/100.2 MB 2.1 MB/s eta 0:00:19
   ------------------------ --------------- 61.6/100.2 MB 2.1 MB/s eta 0:00:19
   ------------------------ --------------- 62.4/100.2 MB 2.1 MB/s eta 0:00:18
   ------------------------- -------------- 63.2/100.2 MB 2.2 MB/s eta 0:00:18
   ------------------------- -------------- 64.0/100.2 MB 2.2 MB/s eta 0:00:17
   ------------------------- -------------- 64.2/100.2 MB 2.2 MB/s eta 0:00:17
   ------------------------- -------------- 64.2/100.2 MB 2.2 MB/s eta 0:00:17
   ------------------------- -------------- 64.2/100.2 MB 2.2 MB/s eta 0:00:17
   ------------------------- -------------- 64.7/100.2 MB 2.1 MB/s eta 0:00:17
   -------------------------- ------------- 65.8/100.2 MB 2.1 MB/s eta 0:00:17
   -------------------------- ------------- 66.8/100.2 MB 2.1 MB/s eta 0:00:16
   -------------------------- ------------- 67.6/100.2 MB 2.1 MB/s eta 0:00:16
   --------------------------- ------------ 68.4/100.2 MB 2.1 MB/s eta 0:00:16
   --------------------------- ------------ 69.2/100.2 MB 2.1 MB/s eta 0:00:15
   --------------------------- ------------ 70.0/100.2 MB 2.1 MB/s eta 0:00:15
   ---------------------------- ----------- 71.0/100.2 MB 2.1 MB/s eta 0:00:14
   ---------------------------- ----------- 71.8/100.2 MB 2.1 MB/s eta 0:00:14
   ---------------------------- ----------- 72.6/100.2 MB 2.1 MB/s eta 0:00:14
   ----------------------------- ---------- 73.4/100.2 MB 2.1 MB/s eta 0:00:13
   ----------------------------- ---------- 74.4/100.2 MB 2.1 MB/s eta 0:00:13
   ------------------------------ --------- 75.2/100.2 MB 2.1 MB/s eta 0:00:12
   ------------------------------ --------- 76.0/100.2 MB 2.1 MB/s eta 0:00:12
   ------------------------------ --------- 76.8/100.2 MB 2.4 MB/s eta 0:00:10
   ------------------------------ --------- 77.6/100.2 MB 2.4 MB/s eta 0:00:10
   ------------------------------- -------- 78.6/100.2 MB 2.4 MB/s eta 0:00:09
   ------------------------------- -------- 79.4/100.2 MB 2.4 MB/s eta 0:00:09
   -------------------------------- ------- 80.2/100.2 MB 2.4 MB/s eta 0:00:09
   -------------------------------- ------- 81.0/100.2 MB 2.5 MB/s eta 0:00:08
   -------------------------------- ------- 82.1/100.2 MB 2.5 MB/s eta 0:00:08
   --------------------------------- ------ 82.8/100.2 MB 2.5 MB/s eta 0:00:08
   --------------------------------- ------ 83.1/100.2 MB 2.5 MB/s eta 0:00:07
   --------------------------------- ------ 83.1/100.2 MB 2.5 MB/s eta 0:00:07
   --------------------------------- ------ 83.4/100.2 MB 2.4 MB/s eta 0:00:07
   --------------------------------- ------ 84.7/100.2 MB 2.5 MB/s eta 0:00:07
   ---------------------------------- ----- 85.5/100.2 MB 2.5 MB/s eta 0:00:06
   ---------------------------------- ----- 86.2/100.2 MB 2.5 MB/s eta 0:00:06
   ---------------------------------- ----- 87.0/100.2 MB 2.5 MB/s eta 0:00:06
   ----------------------------------- ---- 88.1/100.2 MB 2.5 MB/s eta 0:00:05
   ----------------------------------- ---- 88.9/100.2 MB 3.4 MB/s eta 0:00:04
   ----------------------------------- ---- 89.7/100.2 MB 3.4 MB/s eta 0:00:04
   ------------------------------------ --- 90.4/100.2 MB 3.4 MB/s eta 0:00:03
   ------------------------------------ --- 91.2/100.2 MB 3.4 MB/s eta 0:00:03
   ------------------------------------ --- 92.3/100.2 MB 3.4 MB/s eta 0:00:03
   ------------------------------------- -- 93.1/100.2 MB 3.4 MB/s eta 0:00:03
   ------------------------------------- -- 93.8/100.2 MB 3.4 MB/s eta 0:00:02
   ------------------------------------- -- 94.6/100.2 MB 3.4 MB/s eta 0:00:02
   -------------------------------------- - 95.4/100.2 MB 3.4 MB/s eta 0:00:02
   -------------------------------------- - 96.5/100.2 MB 3.4 MB/s eta 0:00:02
   -------------------------------------- - 97.0/100.2 MB 3.4 MB/s eta 0:00:01
   ---------------------------------------  98.0/100.2 MB 3.4 MB/s eta 0:00:01
   ---------------------------------------  98.8/100.2 MB 3.4 MB/s eta 0:00:01
   ---------------------------------------  99.6/100.2 MB 3.4 MB/s eta 0:00:01
   ---------------------------------------  100.1/100.2 MB 3.4 MB/s eta 0:00:01
   ---------------------------------------  100.1/100.2 MB 3.4 MB/s eta 0:00:01
   ---------------------------------------- 100.2/100.2 MB 3.4 MB/s eta 0:00:00
Using cached graphviz-0.21-py3-none-any.whl (47 kB)
Downloading plotly-7.1.0-py3-none-any.whl (9.7 MB)
   ---------------------------------------- 0.0/9.7 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.7 MB ? eta -:--:--
   --- ------------------------------------ 0.8/9.7 MB 2.4 MB/s eta 0:00:04
   ------- -------------------------------- 1.8/9.7 MB 3.1 MB/s eta 0:00:03
   ---------- ----------------------------- 2.6/9.7 MB 3.4 MB/s eta 0:00:03
   -------------- ------------------------- 3.4/9.7 MB 3.4 MB/s eta 0:00:02
   ----------------- ---------------------- 4.2/9.7 MB 3.5 MB/s eta 0:00:02
   ------------------- -------------------- 4.7/9.7 MB 3.5 MB/s eta 0:00:02
   ---------------------- ----------------- 5.5/9.7 MB 3.5 MB/s eta 0:00:02
   ------------------------- -------------- 6.3/9.7 MB 3.5 MB/s eta 0:00:01
   ----------------------------- ---------- 7.1/9.7 MB 3.5 MB/s eta 0:00:01
   -------------------------------- ------- 7.9/9.7 MB 3.5 MB/s eta 0:00:01
   ----------------------------------- ---- 8.7/9.7 MB 3.4 MB/s eta 0:00:01
   ------------------------------------- -- 9.2/9.7 MB 3.5 MB/s eta 0:00:01
   ------------------------------------- -- 9.2/9.7 MB 3.5 MB/s eta 0:00:01
   ------------------------------------- -- 9.2/9.7 MB 3.5 MB/s eta 0:00:01
   ------------------------------------- -- 9.2/9.7 MB 3.5 MB/s eta 0:00:01
   -------------------------------------- - 9.4/9.7 MB 2.6 MB/s eta 0:00:01
   ---------------------------------------- 9.7/9.7 MB 2.6 MB/s eta 0:00:00
Using cached narwhals-2.27.1-py3-none-any.whl (483 kB)
Installing collected packages: narwhals, graphviz, plotly, catboost

   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]

In [114]:
from catboost import CatBoostClassifier

model_cat = CatBoostClassifier(
    auto_class_weights='Balanced',  # or 'SqrtBalanced'
    verbose=0,
    random_state=42
)
model_cat.fit(X_train, y_train)
y_pred_cat = model_cat.predict(X_test)
print(classification_report(y_test, y_pred_cat))

              precision    recall  f1-score   support

           0       0.90      0.76      0.83      1038
           1       0.53      0.75      0.62       369

    accuracy                           0.76      1407
   macro avg       0.71      0.76      0.72      1407
weighted avg       0.80      0.76      0.77      1407

In [116]:
!pip install lightgbm

Collecting lightgbm
  Using cached lightgbm-4.7.0-py3-none-win_amd64.whl.metadata (18 kB)
Requirement already satisfied: narwhals>=1.15 in c:\users\dell\ac\envs\agentic-2-base\lib\site-packages (from lightgbm) (2.27.1)
Requirement already satisfied: numpy>=1.21.3 in c:\users\dell\ac\envs\agentic-2-base\lib\site-packages (from lightgbm) (2.2.6)
Requirement already satisfied: scipy in c:\users\dell\ac\envs\agentic-2-base\lib\site-packages (from lightgbm) (1.15.3)
Using cached lightgbm-4.7.0-py3-none-win_amd64.whl (1.4 MB)
Installing collected packages: lightgbm
Successfully installed lightgbm-4.7.0

In [117]:
from lightgbm import LGBMClassifier

model_lgb = LGBMClassifier(
    scale_pos_weight=scale_pos_weight,
    random_state=42
)
model_lgb.fit(X_train, y_train)
y_pred_lgb = model_lgb.predict(X_test)
print(classification_report(y_test, y_pred_lgb))

[LightGBM] [Info] Number of positive: 1500, number of negative: 4125
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.003207 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 606
[LightGBM] [Info] Number of data points in the train set: 5625, number of used features: 34
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.266667 -> initscore=-1.011601
[LightGBM] [Info] Start training from score -1.011601
              precision    recall  f1-score   support

           0       0.90      0.76      0.82      1038
           1       0.53      0.76      0.62       369

    accuracy                           0.76      1407
   macro avg       0.71      0.76      0.72      1407
weighted avg       0.80      0.76      0.77      1407

In [119]:
!pip install optuna

Collecting optuna
  Using cached optuna-5.0.0-py3-none-any.whl.metadata (14 kB)
Collecting alembic>=1.5.0 (from optuna)
  Using cached alembic-1.20.0-py3-none-any.whl.metadata (7.3 kB)
Collecting colorlog (from optuna)
  Using cached colorlog-6.12.0-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: numpy in c:\users\dell\ac\envs\agentic-2-base\lib\site-packages (from optuna) (2.2.6)
Requirement already satisfied: packaging>=20.0 in c:\users\dell\ac\envs\agentic-2-base\lib\site-packages (from optuna) (24.2)
Requirement already satisfied: sqlalchemy>=1.4.2 in c:\users\dell\ac\envs\agentic-2-base\lib\site-packages (from optuna) (2.0.41)
Requirement already satisfied: tqdm in c:\users\dell\ac\envs\agentic-2-base\lib\site-packages (from optuna) (4.67.1)
Requirement already satisfied: PyYAML in c:\users\dell\ac\envs\agentic-2-base\lib\site-packages (from optuna) (6.0.2)
Collecting Mako (from alembic>=1.5.0->optuna)
  Using cached mako-1.4.3-py3-none-any.whl.metadata (2.9 kB)
Requirement already satisfied: typing-extensions>=4.12 in c:\users\dell\ac\envs\agentic-2-base\lib\site-packages (from alembic>=1.5.0->optuna) (4.13.2)
Requirement already satisfied: greenlet>=1 in c:\users\dell\ac\envs\agentic-2-base\lib\site-packages (from sqlalchemy>=1.4.2->optuna) (3.2.2)
Requirement already satisfied: colorama in c:\users\dell\ac\envs\agentic-2-base\lib\site-packages (from colorlog->optuna) (0.4.6)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\dell\ac\envs\agentic-2-base\lib\site-packages (from Mako->alembic>=1.5.0->optuna) (3.0.2)
Using cached optuna-5.0.0-py3-none-any.whl (442 kB)
Using cached alembic-1.20.0-py3-none-any.whl (268 kB)
Using cached colorlog-6.12.0-py3-none-any.whl (12 kB)
Using cached mako-1.4.3-py3-none-any.whl (80 kB)
Installing collected packages: Mako, colorlog, alembic, optuna

   ---------------------------------------- 0/4 [Mako]
   ---------------------------------------- 0/4 [Mako]
   ---------------------------------------- 0/4 [Mako]
   ---------------------------------------- 0/4 [Mako]
   ---------------------------------------- 0/4 [Mako]
   ---------------------------------------- 0/4 [Mako]
   ---------------------------------------- 0/4 [Mako]
   ---------------------------------------- 0/4 [Mako]
   ---------------------------------------- 0/4 [Mako]
   ---------------------------------------- 0/4 [Mako]
   ---------- ----------------------------- 1/4 [colorlog]
   -------------------- ------------------- 2/4 [alembic]
   -------------------- ------------------- 2/4 [alembic]
   -------------------- ------------------- 2/4 [alembic]
   -------------------- ------------------- 2/4 [alembic]
   -------------------- ------------------- 2/4 [alembic]
   -------------------- ------------------- 2/4 [alembic]
   -------------------- ------------------- 2/4 [alembic]
   -------------------- ------------------- 2/4 [alembic]
   -------------------- ------------------- 2/4 [alembic]
   -------------------- ------------------- 2/4 [alembic]
   -------------------- ------------------- 2/4 [alembic]
   -------------------- ------------------- 2/4 [alembic]
   -------------------- ------------------- 2/4 [alembic]
   -------------------- ------------------- 2/4 [alembic]
   -------------------- ------------------- 2/4 [alembic]
   -------------------- ------------------- 2/4 [alembic]
   -------------------- ------------------- 2/4 [alembic]
   -------------------- ------------------- 2/4 [alembic]
   -------------------- ------------------- 2/4 [alembic]
   ------------------------------ --------- 3/4 [optuna]
   ------------------------------ --------- 3/4 [optuna]
   ------------------------------ --------- 3/4 [optuna]
   ------------------------------ --------- 3/4 [optuna]
   ------------------------------ --------- 3/4 [optuna]
   ------------------------------ --------- 3/4 [optuna]
   ------------------------------ --------- 3/4 [optuna]
   ------------------------------ --------- 3/4 [optuna]
   ------------------------------ --------- 3/4 [optuna]
   ------------------------------ --------- 3/4 [optuna]
   ------------------------------ --------- 3/4 [optuna]
   ------------------------------ --------- 3/4 [optuna]
   ------------------------------ --------- 3/4 [optuna]
   ------------------------------ --------- 3/4 [optuna]
   ------------------------------ --------- 3/4 [optuna]
   ------------------------------ --------- 3/4 [optuna]
   ------------------------------ --------- 3/4 [optuna]
   ------------------------------ --------- 3/4 [optuna]
   ------------------------------ --------- 3/4 [optuna]
   ------------------------------ --------- 3/4 [optuna]
   ------------------------------ --------- 3/4 [optuna]
   ------------------------------ --------- 3/4 [optuna]
   ------------------------------ --------- 3/4 [optuna]
   ------------------------------ --------- 3/4 [optuna]
   ------------------------------ --------- 3/4 [optuna]
   ------------------------------ --------- 3/4 [optuna]
   ------------------------------ --------- 3/4 [optuna]
   ------------------------------ --------- 3/4 [optuna]
   ------------------------------ --------- 3/4 [optuna]
   ------------------------------ --------- 3/4 [optuna]
   ------------------------------ --------- 3/4 [optuna]
   ------------------------------ --------- 3/4 [optuna]
   ------------------------------ --------- 3/4 [optuna]
   ------------------------------ --------- 3/4 [optuna]
   ------------------------------ --------- 3/4 [optuna]
   ------------------------------ --------- 3/4 [optuna]
   ------------------------------ --------- 3/4 [optuna]
   ------------------------------ --------- 3/4 [optuna]
   ------------------------------ --------- 3/4 [optuna]
   ------------------------------ --------- 3/4 [optuna]
   ------------------------------ --------- 3/4 [optuna]
   ------------------------------ --------- 3/4 [optuna]
   ------------------------------ --------- 3/4 [optuna]
   ------------------------------ --------- 3/4 [optuna]
   ------------------------------ --------- 3/4 [optuna]
   ------------------------------ --------- 3/4 [optuna]
   ------------------------------ --------- 3/4 [optuna]
   ------------------------------ --------- 3/4 [optuna]
   ------------------------------ --------- 3/4 [optuna]
   ------------------------------ --------- 3/4 [optuna]
   ------------------------------ --------- 3/4 [optuna]
   ------------------------------ --------- 3/4 [optuna]
   ------------------------------ --------- 3/4 [optuna]
   ------------------------------ --------- 3/4 [optuna]
   ------------------------------ --------- 3/4 [optuna]
   ------------------------------ --------- 3/4 [optuna]
   ---------------------------------------- 4/4 [optuna]

Successfully installed Mako-1.4.3 alembic-1.20.0 colorlog-6.12.0 optuna-5.0.0

## **Optuna fine tuning**

In [120]:
import optuna
from sklearn.model_selection import cross_val_score
from xgboost import XGBClassifier
from sklearn.metrics import f1_score, make_scorer

def objective(trial):
    params = {
        'max_depth': trial.suggest_int('max_depth', 3, 10),
        'learning_rate': trial.suggest_float('learning_rate', 0.01, 0.3, log=True),
        'n_estimators': trial.suggest_int('n_estimators', 100, 1000),
        'subsample': trial.suggest_float('subsample', 0.6, 1.0),
        'colsample_bytree': trial.suggest_float('colsample_bytree', 0.6, 1.0),
        'min_child_weight': trial.suggest_int('min_child_weight', 1, 10),
        'gamma': trial.suggest_float('gamma', 0, 0.5),
        'reg_alpha': trial.suggest_float('reg_alpha', 0, 1),  # L1 regularization
        'reg_lambda': trial.suggest_float('reg_lambda', 0, 2), # L2 regularization
        'scale_pos_weight': trial.suggest_categorical('scale_pos_weight', [1, scale_pos_weight]),
        'random_state': 42,
        'eval_metric': 'logloss'
    }

    model = XGBClassifier(**params)

    # Use F1 for minority class as scorer
    f1_scorer = make_scorer(f1_score, average='binary', pos_label=1)
    score = cross_val_score(model, X_train, y_train, cv=5, scoring=f1_scorer, n_jobs=-1).mean()

    return score

study = optuna.create_study(direction='maximize')
study.optimize(objective, n_trials=100)  # Increase trials for better results

print("Best parameters:", study.best_params)
print("Best CV F1 score:", study.best_value)

# Train final model with best params
best_model_optuna = XGBClassifier(**study.best_params)
best_model_optuna.fit(X_train, y_train)
y_pred_optuna = best_model_optuna.predict(X_test)
print(classification_report(y_test, y_pred_optuna))

c:\Users\DELL\ac\envs\agentic-2-base\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
[I 2026-10-18 23:31:41,434] A new study created in memory with name: no-name-27050a51-39e0-4e57-8391-16cd66f1b7f5
[I 2026-10-18 23:31:59,469] Trial 0 finished with value: 0.5888624798969518 and parameters: {'max_depth': 9, 'learning_rate': 0.21163512956578157, 'n_estimators': 274, 'subsample': 0.8499388581827912, 'colsample_bytree': 0.6923621142643873, 'min_child_weight': 5, 'gamma': 0.42618412187814414, 'reg_alpha': 0.47426797207560667, 'reg_lambda': 1.4627597707814648, 'scale_pos_weight': np.float64(2.75)}. Best is trial 0 with value: 0.5888624798969518.
[I 2026-10-18 23:32:08,436] Trial 1 finished with value: 0.613108485513206 and parameters: {'max_depth': 9, 'learning_rate': 0.01236862899883328, 'n_estimators': 893, 'subsample': 0.9435591083416701, 'colsample_bytree': 0.9308645203563907, 'min_child_weight': 4, 'gamma': 0.46899978736145087, 'reg_alpha': 0.014954399682236552, 'reg_lambda': 1.1670212098802621, 'scale_pos_weight': np.float64(2.75)}. Best is trial 1 with value: 0.613108485513206.
[I 2026-10-18 23:32:12,367] Trial 2 finished with value: 0.5770628440357856 and parameters: {'max_depth': 7, 'learning_rate': 0.01539727495404114, 'n_estimators': 488, 'subsample': 0.6403212358585972, 'colsample_bytree': 0.8071325837306536, 'min_child_weight': 4, 'gamma': 0.4328791635712765, 'reg_alpha': 0.24044926516905696, 'reg_lambda': 1.5077886012994355, 'scale_pos_weight': 1}. Best is trial 1 with value: 0.613108485513206.
[I 2026-10-18 23:32:20,842] Trial 3 finished with value: 0.5771215555019165 and parameters: {'max_depth': 9, 'learning_rate': 0.01421226038978075, 'n_estimators': 804, 'subsample': 0.8542751774351297, 'colsample_bytree': 0.6325890895594143, 'min_child_weight': 2, 'gamma': 0.014505756964256655, 'reg_alpha': 0.18983725567320553, 'reg_lambda': 1.4664806731412272, 'scale_pos_weight': 1}. Best is trial 1 with value: 0.613108485513206.
[I 2026-10-18 23:32:28,579] Trial 4 finished with value: 0.5520823167991395 and parameters: {'max_depth': 10, 'learning_rate': 0.0568746823250931, 'n_estimators': 978, 'subsample': 0.7414731941077173, 'colsample_bytree': 0.8194576967862373, 'min_child_weight': 4, 'gamma': 0.0011198549525749946, 'reg_alpha': 0.358094949974039, 'reg_lambda': 1.5633172286095551, 'scale_pos_weight': 1}. Best is trial 1 with value: 0.613108485513206.
[I 2026-10-18 23:32:32,903] Trial 5 finished with value: 0.6078606010919808 and parameters: {'max_depth': 7, 'learning_rate': 0.029535422070239167, 'n_estimators': 802, 'subsample': 0.8113229675050428, 'colsample_bytree': 0.6755786228362498, 'min_child_weight': 7, 'gamma': 0.3240235014248709, 'reg_alpha': 0.1565994390965495, 'reg_lambda': 0.9481108527124906, 'scale_pos_weight': np.float64(2.75)}. Best is trial 1 with value: 0.613108485513206.
[I 2026-10-18 23:32:35,420] Trial 6 finished with value: 0.5683134982158569 and parameters: {'max_depth': 7, 'learning_rate': 0.1768424602423971, 'n_estimators': 524, 'subsample': 0.8995796167445518, 'colsample_bytree': 0.8642611904703132, 'min_child_weight': 2, 'gamma': 0.4565235169736006, 'reg_alpha': 0.3364313556140063, 'reg_lambda': 0.3643988353338685, 'scale_pos_weight': 1}. Best is trial 1 with value: 0.613108485513206.
[I 2026-10-18 23:32:38,300] Trial 7 finished with value: 0.5784959308522748 and parameters: {'max_depth': 5, 'learning_rate': 0.010170449634191846, 'n_estimators': 369, 'subsample': 0.8832730753315787, 'colsample_bytree': 0.7326058269851723, 'min_child_weight': 10, 'gamma': 0.1847404636760291, 'reg_alpha': 0.5195698228590732, 'reg_lambda': 1.3829628881392475, 'scale_pos_weight': 1}. Best is trial 1 with value: 0.613108485513206.
[I 2026-10-18 23:32:39,849] Trial 8 finished with value: 0.5652023197988383 and parameters: {'max_depth': 8, 'learning_rate': 0.17784423656642273, 'n_estimators': 163, 'subsample': 0.8032949564234235, 'colsample_bytree': 0.8680001854590396, 'min_child_weight': 10, 'gamma': 0.14200775706777163, 'reg_alpha': 0.6994982628718702, 'reg_lambda': 1.5235684979405664, 'scale_pos_weight': 1}. Best is trial 1 with value: 0.613108485513206.
[I 2026-10-18 23:32:44,093] Trial 9 finished with value: 0.6130078024099992 and parameters: {'max_depth': 5, 'learning_rate': 0.04232746113555119, 'n_estimators': 742, 'subsample': 0.9174042725717064, 'colsample_bytree': 0.7897199938525398, 'min_child_weight': 9, 'gamma': 0.044493680844016004, 'reg_alpha': 0.7493261211804922, 'reg_lambda': 1.6310292032068943, 'scale_pos_weight': np.float64(2.75)}. Best is trial 1 with value: 0.613108485513206.
[I 2026-10-18 23:32:48,815] Trial 10 finished with value: 0.6249751826194241 and parameters: {'max_depth': 3, 'learning_rate': 0.014247580996780617, 'n_estimators': 964, 'subsample': 0.9485451670273777, 'colsample_bytree': 0.8409981736208368, 'min_child_weight': 4, 'gamma': 0.4587183216394606, 'reg_alpha': 0.9507367037923881, 'reg_lambda': 1.6293151494283094, 'scale_pos_weight': np.float64(2.75)}. Best is trial 10 with value: 0.6249751826194241.
[I 2026-10-18 23:32:57,480] Trial 11 finished with value: 0.6075640029358482 and parameters: {'max_depth': 9, 'learning_rate': 0.010318035685479059, 'n_estimators': 775, 'subsample': 0.9161725746075347, 'colsample_bytree': 0.9537705844219152, 'min_child_weight': 2, 'gamma': 0.439604306349361, 'reg_alpha': 0.2151649921411841, 'reg_lambda': 1.4472585727053175, 'scale_pos_weight': np.float64(2.75)}. Best is trial 10 with value: 0.6249751826194241.
[I 2026-10-18 23:33:01,355] Trial 12 finished with value: 0.6211817980235814 and parameters: {'max_depth': 5, 'learning_rate': 0.015159851922197676, 'n_estimators': 808, 'subsample': 0.99812091949994, 'colsample_bytree': 0.9998257498747838, 'min_child_weight': 6, 'gamma': 0.44384359807660007, 'reg_alpha': 0.5314343446811447, 'reg_lambda': 1.9568157198041125, 'scale_pos_weight': np.float64(2.75)}. Best is trial 10 with value: 0.6249751826194241.
[I 2026-10-18 23:33:05,618] Trial 13 finished with value: 0.6276054776002286 and parameters: {'max_depth': 3, 'learning_rate': 0.017081710762660744, 'n_estimators': 998, 'subsample': 0.9596221563466444, 'colsample_bytree': 0.8844751929838462, 'min_child_weight': 4, 'gamma': 0.4495842287027098, 'reg_alpha': 0.40383569390743723, 'reg_lambda': 1.207350438670138, 'scale_pos_weight': np.float64(2.75)}. Best is trial 13 with value: 0.6276054776002286.
[I 2026-10-18 23:33:09,709] Trial 14 finished with value: 0.6216362743218439 and parameters: {'max_depth': 4, 'learning_rate': 0.03685174962615861, 'n_estimators': 953, 'subsample': 0.9894744703287032, 'colsample_bytree': 0.8414658104037204, 'min_child_weight': 5, 'gamma': 0.33871946794591434, 'reg_alpha': 0.4721083253512274, 'reg_lambda': 1.8039020964162242, 'scale_pos_weight': np.float64(2.75)}. Best is trial 13 with value: 0.6276054776002286.
[I 2026-10-18 23:33:14,047] Trial 15 finished with value: 0.6187722868029895 and parameters: {'max_depth': 5, 'learning_rate': 0.01856097762021065, 'n_estimators': 680, 'subsample': 0.9139787993548418, 'colsample_bytree': 0.9230858650682976, 'min_child_weight': 4, 'gamma': 0.36149182204812547, 'reg_alpha': 0.7008639243337142, 'reg_lambda': 1.522516734306547, 'scale_pos_weight': np.float64(2.75)}. Best is trial 13 with value: 0.6276054776002286.
[I 2026-10-18 23:33:19,608] Trial 16 finished with value: 0.6289884922095995 and parameters: {'max_depth': 4, 'learning_rate': 0.012542528061864677, 'n_estimators': 913, 'subsample': 0.9061034849133605, 'colsample_bytree': 0.7612826499660635, 'min_child_weight': 3, 'gamma': 0.4723068496481224, 'reg_alpha': 0.7867725217826284, 'reg_lambda': 1.8659423993244757, 'scale_pos_weight': np.float64(2.75)}. Best is trial 16 with value: 0.6289884922095995.
[I 2026-10-18 23:33:24,557] Trial 17 finished with value: 0.6270281220568593 and parameters: {'max_depth': 5, 'learning_rate': 0.011193506039740156, 'n_estimators': 990, 'subsample': 0.970731880093099, 'colsample_bytree': 0.6810752362248943, 'min_child_weight': 1, 'gamma': 0.38796364761475965, 'reg_alpha': 0.7363543328492194, 'reg_lambda': 1.7888360610103216, 'scale_pos_weight': np.float64(2.75)}. Best is trial 16 with value: 0.6289884922095995.
[I 2026-10-18 23:33:28,679] Trial 18 finished with value: 0.6274624314023595 and parameters: {'max_depth': 3, 'learning_rate': 0.016796555170744645, 'n_estimators': 918, 'subsample': 0.8815337667928771, 'colsample_bytree': 0.7448174300538392, 'min_child_weight': 4, 'gamma': 0.4371797671893964, 'reg_alpha': 0.5579632003940904, 'reg_lambda': 1.127267484903425, 'scale_pos_weight': np.float64(2.75)}. Best is trial 16 with value: 0.6289884922095995.
[I 2026-10-18 23:33:31,284] Trial 19 finished with value: 0.6300470427473696 and parameters: {'max_depth': 3, 'learning_rate': 0.013731521432656263, 'n_estimators': 624, 'subsample': 0.8883718343480516, 'colsample_bytree': 0.7947181787777008, 'min_child_weight': 6, 'gamma': 0.45374826989434935, 'reg_alpha': 0.8985381549469866, 'reg_lambda': 1.8062042959914573, 'scale_pos_weight': np.float64(2.75)}. Best is trial 19 with value: 0.6300470427473696.
[I 2026-10-18 23:33:36,006] Trial 20 finished with value: 0.6175867076493864 and parameters: {'max_depth': 6, 'learning_rate': 0.021405494404808302, 'n_estimators': 669, 'subsample': 0.8840605573757856, 'colsample_bytree': 0.7468800733616079, 'min_child_weight': 1, 'gamma': 0.4286543133168203, 'reg_alpha': 0.8845396067119543, 'reg_lambda': 1.7304540146752676, 'scale_pos_weight': np.float64(2.75)}. Best is trial 19 with value: 0.6300470427473696.
[I 2026-10-18 23:33:39,928] Trial 21 finished with value: 0.6225149912586169 and parameters: {'max_depth': 3, 'learning_rate': 0.02840360436523701, 'n_estimators': 984, 'subsample': 0.9959653010907012, 'colsample_bytree': 0.8302642058241044, 'min_child_weight': 3, 'gamma': 0.45944865278133407, 'reg_alpha': 0.509790056711189, 'reg_lambda': 1.1855881968084228, 'scale_pos_weight': np.float64(2.75)}. Best is trial 19 with value: 0.6300470427473696.
[I 2026-10-18 23:33:43,899] Trial 22 finished with value: 0.6194751369293034 and parameters: {'max_depth': 4, 'learning_rate': 0.029278302574770966, 'n_estimators': 845, 'subsample': 0.9782794575310504, 'colsample_bytree': 0.8808578950786902, 'min_child_weight': 3, 'gamma': 0.4291717304230973, 'reg_alpha': 0.7225510268625772, 'reg_lambda': 1.2206799923518, 'scale_pos_weight': np.float64(2.75)}. Best is trial 19 with value: 0.6300470427473696.
[I 2026-10-18 23:33:48,736] Trial 23 finished with value: 0.62603126123069 and parameters: {'max_depth': 4, 'learning_rate': 0.010418115600427533, 'n_estimators': 861, 'subsample': 0.94052814183119, 'colsample_bytree': 0.8786145134691561, 'min_child_weight': 3, 'gamma': 0.389428105119473, 'reg_alpha': 0.323800271370329, 'reg_lambda': 1.0654929848495707, 'scale_pos_weight': np.float64(2.75)}. Best is trial 19 with value: 0.6300470427473696.
[I 2026-10-18 23:33:52,506] Trial 24 finished with value: 0.6283159398370938 and parameters: {'max_depth': 3, 'learning_rate': 0.01730386176607792, 'n_estimators': 757, 'subsample': 0.8994966573236569, 'colsample_bytree': 0.6812291107474568, 'min_child_weight': 5, 'gamma': 0.4911132192214237, 'reg_alpha': 0.8658109902554705, 'reg_lambda': 1.807925744583662, 'scale_pos_weight': np.float64(2.75)}. Best is trial 19 with value: 0.6300470427473696.
[I 2026-10-18 23:33:57,247] Trial 25 finished with value: 0.6277356683850026 and parameters: {'max_depth': 4, 'learning_rate': 0.02271976157699563, 'n_estimators': 912, 'subsample': 0.8687238951460935, 'colsample_bytree': 0.6853754290551011, 'min_child_weight': 6, 'gamma': 0.47526582027718445, 'reg_alpha': 0.8033207438405278, 'reg_lambda': 1.8232252748591922, 'scale_pos_weight': np.float64(2.75)}. Best is trial 19 with value: 0.6300470427473696.
[I 2026-10-18 23:34:01,342] Trial 26 finished with value: 0.62750475711575 and parameters: {'max_depth': 4, 'learning_rate': 0.010522894074420214, 'n_estimators': 951, 'subsample': 0.9811916328126052, 'colsample_bytree': 0.7243869017737428, 'min_child_weight': 5, 'gamma': 0.4865697969378221, 'reg_alpha': 0.9016322803259137, 'reg_lambda': 1.8873776321651454, 'scale_pos_weight': np.float64(2.75)}. Best is trial 19 with value: 0.6300470427473696.
[I 2026-10-18 23:34:04,572] Trial 27 finished with value: 0.6238716003033338 and parameters: {'max_depth': 3, 'learning_rate': 0.039313361830584787, 'n_estimators': 735, 'subsample': 0.8590006807879942, 'colsample_bytree': 0.7212717624150483, 'min_child_weight': 7, 'gamma': 0.46650416477877876, 'reg_alpha': 0.8710512738008128, 'reg_lambda': 1.7330281068177569, 'scale_pos_weight': np.float64(2.75)}. Best is trial 19 with value: 0.6300470427473696.
[I 2026-10-18 23:34:08,034] Trial 28 finished with value: 0.628980378931485 and parameters: {'max_depth': 3, 'learning_rate': 0.0213260223201176, 'n_estimators': 799, 'subsample': 0.9334300986498533, 'colsample_bytree': 0.6910124397483884, 'min_child_weight': 6, 'gamma': 0.3843471223795081, 'reg_alpha': 0.8898730492411245, 'reg_lambda': 1.8956616489184441, 'scale_pos_weight': np.float64(2.75)}. Best is trial 19 with value: 0.6300470427473696.
[I 2026-10-18 23:34:11,460] Trial 29 finished with value: 0.6309626687616327 and parameters: {'max_depth': 3, 'learning_rate': 0.010804261803047327, 'n_estimators': 770, 'subsample': 0.9530940408203126, 'colsample_bytree': 0.7386852453159732, 'min_child_weight': 4, 'gamma': 0.45687064137489025, 'reg_alpha': 0.8566515016216448, 'reg_lambda': 1.6769924801231149, 'scale_pos_weight': np.float64(2.75)}. Best is trial 29 with value: 0.6309626687616327.
[I 2026-10-18 23:34:14,967] Trial 30 finished with value: 0.6304606832463502 and parameters: {'max_depth': 3, 'learning_rate': 0.024795311324855497, 'n_estimators': 789, 'subsample': 0.9495514368090585, 'colsample_bytree': 0.7565758233910107, 'min_child_weight': 4, 'gamma': 0.3893473768345593, 'reg_alpha': 0.82860335157034, 'reg_lambda': 1.5648847544574833, 'scale_pos_weight': np.float64(2.75)}. Best is trial 29 with value: 0.6309626687616327.
[I 2026-10-18 23:34:19,797] Trial 31 finished with value: 0.6260255598774961 and parameters: {'max_depth': 4, 'learning_rate': 0.018322673277701537, 'n_estimators': 832, 'subsample': 0.9251198426516793, 'colsample_bytree': 0.7649242063633143, 'min_child_weight': 5, 'gamma': 0.44741848293376324, 'reg_alpha': 0.8120530817640951, 'reg_lambda': 1.832192609545081, 'scale_pos_weight': np.float64(2.75)}. Best is trial 29 with value: 0.6309626687616327.
[I 2026-10-18 23:34:23,755] Trial 32 finished with value: 0.6292797624663098 and parameters: {'max_depth': 3, 'learning_rate': 0.015082350330389236, 'n_estimators': 829, 'subsample': 0.8823482164596946, 'colsample_bytree': 0.8042217427061031, 'min_child_weight': 3, 'gamma': 0.45748302724034556, 'reg_alpha': 0.9662121403385745, 'reg_lambda': 1.7934109828800524, 'scale_pos_weight': np.float64(2.75)}. Best is trial 29 with value: 0.6309626687616327.
[I 2026-10-18 23:34:26,186] Trial 33 finished with value: 0.6262865186457506 and parameters: {'max_depth': 3, 'learning_rate': 0.022456382871071212, 'n_estimators': 655, 'subsample': 0.9278429673318712, 'colsample_bytree': 0.7803602876794218, 'min_child_weight': 3, 'gamma': 0.40466760665636625, 'reg_alpha': 0.9245062978437838, 'reg_lambda': 1.604129430103884, 'scale_pos_weight': np.float64(2.75)}. Best is trial 29 with value: 0.6309626687616327.
[I 2026-10-18 23:34:28,627] Trial 34 finished with value: 0.6292074118258232 and parameters: {'max_depth': 3, 'learning_rate': 0.01726049613124607, 'n_estimators': 601, 'subsample': 0.9434838987063365, 'colsample_bytree': 0.687663064153683, 'min_child_weight': 3, 'gamma': 0.45119143834570014, 'reg_alpha': 0.9044699451671547, 'reg_lambda': 1.5137198340177735, 'scale_pos_weight': np.float64(2.75)}. Best is trial 29 with value: 0.6309626687616327.
[I 2026-10-18 23:34:31,201] Trial 35 finished with value: 0.6288712639061005 and parameters: {'max_depth': 3, 'learning_rate': 0.010565901945668916, 'n_estimators': 711, 'subsample': 0.9886445845741603, 'colsample_bytree': 0.6597677275165854, 'min_child_weight': 3, 'gamma': 0.4542283068813673, 'reg_alpha': 0.7579423629905796, 'reg_lambda': 1.6151076650828433, 'scale_pos_weight': np.float64(2.75)}. Best is trial 29 with value: 0.6309626687616327.
[I 2026-10-18 23:34:33,823] Trial 36 finished with value: 0.6255901113571055 and parameters: {'max_depth': 4, 'learning_rate': 0.02033715544258192, 'n_estimators': 622, 'subsample': 0.8519172957207929, 'colsample_bytree': 0.7721050076659796, 'min_child_weight': 7, 'gamma': 0.40190822256486514, 'reg_alpha': 0.8950524663462265, 'reg_lambda': 1.7101857574450934, 'scale_pos_weight': np.float64(2.75)}. Best is trial 29 with value: 0.6309626687616327.
[I 2026-10-18 23:34:36,940] Trial 37 finished with value: 0.6283040302272473 and parameters: {'max_depth': 4, 'learning_rate': 0.016258398448773706, 'n_estimators': 757, 'subsample': 0.9788329688991013, 'colsample_bytree': 0.6868984125435991, 'min_child_weight': 5, 'gamma': 0.4493849827799971, 'reg_alpha': 0.9334152870878205, 'reg_lambda': 1.7192824440625074, 'scale_pos_weight': np.float64(2.75)}. Best is trial 29 with value: 0.6309626687616327.
[I 2026-10-18 23:34:41,200] Trial 38 finished with value: 0.6282460011026776 and parameters: {'max_depth': 4, 'learning_rate': 0.013768362965722312, 'n_estimators': 848, 'subsample': 0.8486631900828331, 'colsample_bytree': 0.7052195091515763, 'min_child_weight': 2, 'gamma': 0.45286214985802936, 'reg_alpha': 0.9576058042003975, 'reg_lambda': 1.7819687415118002, 'scale_pos_weight': np.float64(2.75)}. Best is trial 29 with value: 0.6309626687616327.
[I 2026-10-18 23:34:45,087] Trial 39 finished with value: 0.6253296110654165 and parameters: {'max_depth': 3, 'learning_rate': 0.024959561857846386, 'n_estimators': 914, 'subsample': 0.9300298857254952, 'colsample_bytree': 0.7518476441511489, 'min_child_weight': 4, 'gamma': 0.44738224979426794, 'reg_alpha': 0.8791269389860611, 'reg_lambda': 1.6686467861474543, 'scale_pos_weight': np.float64(2.75)}. Best is trial 29 with value: 0.6309626687616327.
[I 2026-10-18 23:34:48,616] Trial 40 finished with value: 0.6255327819154588 and parameters: {'max_depth': 3, 'learning_rate': 0.02959671907676739, 'n_estimators': 817, 'subsample': 0.8628394309960399, 'colsample_bytree': 0.8195530543993379, 'min_child_weight': 2, 'gamma': 0.41384576741654044, 'reg_alpha': 0.9022383580392488, 'reg_lambda': 1.964432003008568, 'scale_pos_weight': np.float64(2.75)}. Best is trial 29 with value: 0.6309626687616327.
[I 2026-10-18 23:34:52,175] Trial 41 finished with value: 0.6230914097698594 and parameters: {'max_depth': 4, 'learning_rate': 0.02113169940107178, 'n_estimators': 648, 'subsample': 0.9226002130793283, 'colsample_bytree': 0.79335444664202, 'min_child_weight': 5, 'gamma': 0.47145517142778226, 'reg_alpha': 0.7468926458545034, 'reg_lambda': 1.8554476925917915, 'scale_pos_weight': np.float64(2.75)}. Best is trial 29 with value: 0.6309626687616327.
[I 2026-10-18 23:34:55,711] Trial 42 finished with value: 0.6312976648334739 and parameters: {'max_depth': 3, 'learning_rate': 0.012989018979219757, 'n_estimators': 709, 'subsample': 0.9707452282663501, 'colsample_bytree': 0.7144400672812448, 'min_child_weight': 2, 'gamma': 0.4708034740908483, 'reg_alpha': 0.8844613128475104, 'reg_lambda': 1.9216672770801138, 'scale_pos_weight': np.float64(2.75)}. Best is trial 42 with value: 0.6312976648334739.

Best parameters: {'max_depth': 4, 'learning_rate': 0.011480197816950718, 'n_estimators': 750, 'subsample': 0.9428859647594939, 'colsample_bytree': 0.6617142644951981, 'min_child_weight': 2, 'gamma': 0.4575146714903624, 'reg_alpha': 0.9839765856262228, 'reg_lambda': 1.9216369996764118, 'scale_pos_weight': np.float64(2.75)}
Best CV F1 score: 0.6342411569269533
              precision    recall  f1-score   support

           0       0.91      0.74      0.81      1038
           1       0.51      0.78      0.62       369

    accuracy                           0.75      1407
   macro avg       0.71      0.76      0.72      1407
weighted avg       0.80      0.75      0.76      1407

In [121]:
# Save this model

import joblib

# Save the best model to a .pkl file
joblib.dump(best_model_optuna, 'best_optuna_churn_model.pkl')

print("Best model successfully saved as 'best_optuna_churn_model.pkl'")

Best model successfully saved as 'best_optuna_churn_model.pkl'

In [122]:
# Save this model

import joblib

# Save the best model to a .pkl file
joblib.dump(model_ada_weighted, 'ada_boost_churn_model.pkl')

print("Best model successfully saved as 'ada_boost_churn_model.pkl'")

Best model successfully saved as 'ada_boost_churn_model.pkl'

In machine learning, SMOTE, SMOTE-ENN, and ADASYN are feature engineering techniques used to handle class imbalance by generating synthetic data for the minority class.
Here is a breakdown of their functionality and implementation using imbalanced-learn.

1. SMOTE (Synthetic Minority Over-sampling Technique)

• Functionality: SMOTE works by selecting a minority class instance and finding its \(k\)-nearest neighbors. It then randomly selects one of these neighbors and creates a new synthetic instance at a random point along the line segment connecting the two features. This expands the decision boundary of the minority class rather than simply duplicating data points.
• Limitation: It treats all minority instances equally, generating synthetic data without considering if a point is a noisy outlier or located deep within the majority class territory.

Python Implementation Example

python
from imblearn.over_sampling import SMOTE
from sklearn.datasets import make_classification
from collections import Counter

# Generate imbalanced dataset (90% majority, 10% minority)
X, y = make_classification(n_classes=2, class_sep=2, weights=[0.9, 0.1], 
                           n_informative=3, n_redundant=1, flip_y=0, 
                           n_features=20, n_clusters_per_class=1, 
                           n_samples=1000, random_state=42)

print(f"Original class distribution: {Counter(y)}")

# Apply SMOTE
smote = SMOTE(random_state=42)
X_smote, y_smote = smote.fit_resample(X, y)

print(f"Resampled class distribution (SMOTE): {Counter(y_smote)}")
Use code with caution.

2. ADASYN (Adaptive Synthetic Sampling)

• Functionality: ADASYN builds upon SMOTE but adds an adaptive mechanism. It calculates a density distribution for different minority class examples based on how many majority class neighbors they have. It then generates more synthetic data for minority instances that are harder to learn (those surrounded by majority class points) and fewer for instances in easier regions.
• Advantage: It shifts the learning focus toward the highly ambiguous decision boundaries where the model is most likely to make errors.

Python Implementation Example

python
from imblearn.over_sampling import ADASYN

# Apply ADASYN on the same original dataset (X, y)
adasyn = ADASYN(random_state=42)
X_ada, y_ada = adasyn.fit_resample(X, y)

print(f"Resampled class distribution (ADASYN): {Counter(y_ada)}")
Use code with caution.

3. SMOTE-ENN (SMOTE + Edited Nearest Neighbors)

• Functionality: SMOTE-ENN is a hybrid method that combines over-sampling and under-sampling.
	1. Over-sampling (SMOTE): First, it applies SMOTE to over-sample the minority class.
	2. Under-sampling (ENN): Next, it uses ENN as a cleaning step. It examines every data point; if a point's \(k\)-nearest neighbors belong to a different class (or a majority of them do), that point is removed.
• Advantage: SMOTE often creates noisy synthetic points in overlapping class regions. ENN cleans this up, creating a clearer, more distinct decision boundary between classes, which typically improves classifier performance.

Python Implementation Example

python
from imblearn.combine import SMOTEENN

# Apply SMOTE-ENN on the same original dataset (X, y)
smote_enn = SMOTEENN(random_state=42)
X_smenn, y_smenn = smote_enn.fit_resample(X, y)

print(f"Resampled class distribution (SMOTE-ENN): {Counter(y_smenn)}")
Use code with caution.

Comparison Summary


Technique	Approach Type	Best Used When...	Potential Drawback
SMOTE	Over-sampling	Data regions are clean and linear boundaries are sufficient.	Can introduce noise by bridging outliers.
ADASYN	Adaptive Over-sampling	Boundaries are complex; model struggles specifically near class borders.	Can over-focus on extreme outliers/noise.
SMOTE-ENN	Hybrid (Over + Under)	Heavy class overlap exists; you need a highly clean decision boundary.	Can reduce overall dataset size aggressively.